/**
 * AURA (Autonomous Urgent Response Agent) - Persistent SQL Memory Engine
 * =====================================================================
 * 
 * Feature Description & Architecture:
 * This module provides high-speed, embedded, persistent SQL memory storage for AURA's
 * emergency call intake operations. It addresses two distinct memory lifecycles:
 * 
 * 1. Short-Term Memory:
 *    Within an active call, every utterance, acoustic tone measurement, speaker disentanglement,
 *    and system directive is committed sequentially as a memory turn. This short-term
 *    memory allows the Gemini 3.8 Flash model to maintain conversational grounding, remember
 *    crucial details (e.g. caller said "second floor", "gas leak bay 14"), and respond
 *    with continuity across turns.
 * 
 * 2. Persistent Long-Term Memory & Session Separation:
 *    Every new 911 call is treated as a separate, isolated session identified by a unique
 *    `session_id` (e.g., "SESSION-CALL-99124-1711234567") and `call_id`. Past sessions
 *    persist across server restarts in the SQLite database (`db/aura_memory.sqlite`), allowing
 *    post-incident audit trails, supervisor reviews, and historical context retrieval.
 * 
 * 3. Token Tracking & Context Management:
 *    Every memory turn tracks its calculated token count (text + metadata tokens). The session
 *    maintains an aggregate `token_count`. When cumulative tokens reach or exceed the 20,000
 *    token limit, the Summarization Middleware automatically activates to distill the older
 *    transcript turns into a high-fidelity tactical incident summary while maintaining
 *    the latest active dialogue turns.
 * 
 * Tables Managed:
 * - `sessions`: Stores call session metadata, language, status, aggregate token count, and current executive summary.
 * - `memory_turns`: Stores individual dialogue turns, speaker tags, verbatim text, translations, tone metrics, and barge-in flags.
 * - `summaries`: Stores historical context summaries generated by the 20K token middleware.
 */

import { DatabaseSync } from "node:sqlite";
import path from "node:path";
import fs from "node:fs";
import { AURA_CONFIG } from "../src/config/auraConfig.ts";

export interface SessionRecord {
  id?: number;
  session_id: string;
  call_id: string;
  caller_language: string;
  caller_language_code: string;
  incident_type?: string;
  location?: string;
  status: string;
  summary?: string;
  token_count: number;
  is_summarized: number;
  created_at: string;
  updated_at: string;
}

export interface MemoryTurnRecord {
  id?: number;
  session_id: string;
  turn_index: number;
  speaker: "CALLER" | "AURA" | "SYSTEM";
  text: string;
  english_translation?: string;
  tone_metrics_json?: string;
  intent?: string;
  is_barge_in: number;
  token_count: number;
  timestamp: string;
}

export interface SummaryRecord {
  id?: number;
  session_id: string;
  summary_text: string;
  tokens_summarized: number;
  range_start_turn: number;
  range_end_turn: number;
  created_at: string;
}

let dbInstance: DatabaseSync | null = null;

/**
 * Initializes and returns the SQLite database instance, creating tables and indices if not present.
 * 
 * @returns DatabaseSync instance for SQL queries.
 */
export function getSqlMemoryDb(): DatabaseSync {
  console.info("[SQL MEMORY] getSqlMemoryDb called.");
  if (dbInstance) {
    return dbInstance;
  }

  const dbDir = path.resolve(process.cwd(), "db");
  if (!fs.existsSync(dbDir)) {
    console.info(`[SQL MEMORY] Creating database directory: ${dbDir}`);
    fs.mkdirSync(dbDir, { recursive: true });
  }

  const dbPath = path.resolve(process.cwd(), AURA_CONFIG.memory.dbFilePath);
  console.info(`[SQL MEMORY] Connecting to SQLite database at: ${dbPath}`);
  dbInstance = new DatabaseSync(dbPath);

  // Enable WAL mode for high concurrency
  dbInstance.exec("PRAGMA journal_mode = WAL;");
  dbInstance.exec("PRAGMA synchronous = NORMAL;");

  // Create Sessions table
  dbInstance.exec(`
    CREATE TABLE IF NOT EXISTS sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT UNIQUE NOT NULL,
      call_id TEXT NOT NULL,
      caller_language TEXT DEFAULT 'English',
      caller_language_code TEXT DEFAULT 'en',
      incident_type TEXT DEFAULT 'Unclassified Emergency',
      location TEXT DEFAULT 'Location Unconfirmed',
      status TEXT DEFAULT 'ACTIVE',
      summary TEXT DEFAULT NULL,
      token_count INTEGER DEFAULT 0,
      is_summarized INTEGER DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_sessions_call_id ON sessions(call_id);
    CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON sessions(created_at DESC);
  `);

  // Create Memory Turns table
  dbInstance.exec(`
    CREATE TABLE IF NOT EXISTS memory_turns (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      turn_index INTEGER NOT NULL,
      speaker TEXT NOT NULL,
      text TEXT NOT NULL,
      english_translation TEXT DEFAULT NULL,
      tone_metrics_json TEXT DEFAULT NULL,
      intent TEXT DEFAULT NULL,
      is_barge_in INTEGER DEFAULT 0,
      token_count INTEGER DEFAULT 0,
      timestamp TEXT NOT NULL,
      FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_memory_turns_session ON memory_turns(session_id, turn_index);
  `);

  // Create Summaries table
  dbInstance.exec(`
    CREATE TABLE IF NOT EXISTS summaries (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      session_id TEXT NOT NULL,
      summary_text TEXT NOT NULL,
      tokens_summarized INTEGER NOT NULL,
      range_start_turn INTEGER NOT NULL,
      range_end_turn INTEGER NOT NULL,
      created_at TEXT NOT NULL,
      FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
    );
    CREATE INDEX IF NOT EXISTS idx_summaries_session ON summaries(session_id);
  `);

  console.info("[SQL MEMORY] Tables and indices verified successfully.");
  return dbInstance;
}

/**
 * Estimates token count based on text length and metadata JSON.
 * Average approximation: ~4 characters per token for multi-language text.
 * 
 * @param text The text or stringified data.
 * @returns Estimated number of tokens.
 */
export function estimateTokens(text: string): number {
  if (!text) return 0;
  return Math.ceil(text.length / AURA_CONFIG.memory.avgCharsPerToken) + 4; // Add 4 overhead tokens for role/turn formatting
}

/**
 * Creates or retrieves a session record in the SQL memory store.
 * Every new emergency call starts with an isolated session.
 * 
 * @param callId Unique 911 Call Identifier (e.g. CALL-99124).
 * @param callerLanguage Spoken caller language (e.g. Spanish, English).
 * @param callerLanguageCode 2-letter language code (e.g. es, en).
 * @returns The created or existing SessionRecord.
 */
export function createSession(callId: string, callerLanguage: string = "English", callerLanguageCode: string = "en"): SessionRecord {
  console.info(`[SQL MEMORY] createSession called with callId="${callId}", lang="${callerLanguage}" (${callerLanguageCode})`);
  const db = getSqlMemoryDb();
  const sessionId = `SESSION-${callId}-${Date.now()}`;
  const now = new Date().toISOString();

  const insertStmt = db.prepare(`
    INSERT INTO sessions (
      session_id, call_id, caller_language, caller_language_code,
      incident_type, location, status, token_count, is_summarized,
      created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  insertStmt.run(
    sessionId,
    callId,
    callerLanguage,
    callerLanguageCode,
    "Emergency Crisis Intake",
    "Awaiting Location Confirmation",
    "ACTIVE",
    0,
    0,
    now,
    now
  );

  const session = getSession(sessionId);
  if (!session) {
    throw new Error(`Failed to retrieve newly created session: ${sessionId}`);
  }
  console.info(`[SQL MEMORY] Session created successfully: ${sessionId}`);
  return session;
}

/**
 * Retrieves a session by its unique session ID.
 * 
 * @param sessionId The unique session string.
 * @returns The SessionRecord or null if not found.
 */
export function getSession(sessionId: string): SessionRecord | null {
  console.info(`[SQL MEMORY] getSession called with sessionId="${sessionId}"`);
  const db = getSqlMemoryDb();
  const row = db.prepare("SELECT * FROM sessions WHERE session_id = ?").get(sessionId) as any;
  if (!row) return null;
  return {
    ...row,
    token_count: Number(row.token_count || 0),
    is_summarized: Number(row.is_summarized || 0)
  };
}

/**
 * Retrieves the most recent active session for a specific callId.
 * 
 * @param callId The Call Identifier (e.g. CALL-99124).
 * @returns The matching SessionRecord or null.
 */
export function getLatestSessionByCallId(callId: string): SessionRecord | null {
  console.info(`[SQL MEMORY] getLatestSessionByCallId called with callId="${callId}"`);
  const db = getSqlMemoryDb();
  const row = db.prepare("SELECT * FROM sessions WHERE call_id = ? ORDER BY id DESC LIMIT 1").get(callId) as any;
  if (!row) return null;
  return {
    ...row,
    token_count: Number(row.token_count || 0),
    is_summarized: Number(row.is_summarized || 0)
  };
}

/**
 * Lists all call sessions stored in the persistent SQL memory database.
 * 
 * @param limit Maximum number of sessions to return.
 * @returns Array of SessionRecord.
 */
export function listSessions(limit: number = 20): SessionRecord[] {
  console.info(`[SQL MEMORY] listSessions called with limit=${limit}`);
  const db = getSqlMemoryDb();
  const rows = db.prepare("SELECT * FROM sessions ORDER BY created_at DESC LIMIT ?").all(limit) as any[];
  return rows.map((r) => ({
    ...r,
    token_count: Number(r.token_count || 0),
    is_summarized: Number(r.is_summarized || 0)
  }));
}

/**
 * Appends a conversation turn to the short-term SQL memory of the given session.
 * 
 * @param turn Turn record parameters to persist.
 * @returns The created MemoryTurnRecord with turn_index and token count.
 */
export function addMemoryTurn(turn: {
  sessionId: string;
  speaker: "CALLER" | "AURA" | "SYSTEM";
  text: string;
  englishTranslation?: string;
  toneMetrics?: any;
  intent?: string;
  isBargeIn?: boolean;
}): MemoryTurnRecord {
  console.info(`[SQL MEMORY] addMemoryTurn called for session="${turn.sessionId}", speaker="${turn.speaker}", text="${turn.text.substring(0, 40)}..."`);
  const db = getSqlMemoryDb();
  const session = getSession(turn.sessionId);
  if (!session) {
    throw new Error(`Session ${turn.sessionId} not found in SQL memory database.`);
  }

  // Get current turn count for this session
  const countRow = db.prepare("SELECT COUNT(*) as count FROM memory_turns WHERE session_id = ?").get(turn.sessionId) as any;
  const nextTurnIndex = (countRow?.count || 0) + 1;

  // Calculate tokens for this turn
  const turnTokens = estimateTokens(turn.text) + (turn.englishTranslation ? estimateTokens(turn.englishTranslation) : 0);
  const toneJson = turn.toneMetrics ? JSON.stringify(turn.toneMetrics) : null;
  const timestamp = new Date().toISOString();

  const insertStmt = db.prepare(`
    INSERT INTO memory_turns (
      session_id, turn_index, speaker, text, english_translation,
      tone_metrics_json, intent, is_barge_in, token_count, timestamp
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  insertStmt.run(
    turn.sessionId,
    nextTurnIndex,
    turn.speaker,
    turn.text,
    turn.englishTranslation || null,
    toneJson,
    turn.intent || null,
    turn.isBargeIn ? 1 : 0,
    turnTokens,
    timestamp
  );

  // Update session aggregate token count
  const updatedTokens = session.token_count + turnTokens;
  db.prepare(`
    UPDATE sessions 
    SET token_count = ?, updated_at = ?
    WHERE session_id = ?
  `).run(updatedTokens, timestamp, turn.sessionId);

  console.info(`[SQL MEMORY] Turn #${nextTurnIndex} recorded. Session "${turn.sessionId}" token count now: ${updatedTokens}`);

  return {
    session_id: turn.sessionId,
    turn_index: nextTurnIndex,
    speaker: turn.speaker,
    text: turn.text,
    english_translation: turn.englishTranslation,
    tone_metrics_json: toneJson || undefined,
    intent: turn.intent,
    is_barge_in: turn.isBargeIn ? 1 : 0,
    token_count: turnTokens,
    timestamp
  };
}

/**
 * Retrieves all memory turns for a session from SQL memory.
 * 
 * @param sessionId The session identifier.
 * @returns Array of MemoryTurnRecord in chronological order.
 */
export function getSessionTurns(sessionId: string): MemoryTurnRecord[] {
  console.info(`[SQL MEMORY] getSessionTurns called for session="${sessionId}"`);
  const db = getSqlMemoryDb();
  const rows = db.prepare("SELECT * FROM memory_turns WHERE session_id = ? ORDER BY turn_index ASC").all(sessionId) as any[];
  return rows.map((r) => ({
    ...r,
    turn_index: Number(r.turn_index),
    is_barge_in: Number(r.is_barge_in || 0),
    token_count: Number(r.token_count || 0)
  }));
}

/**
 * Updates session metadata (such as detected location, incident type, language, status, or summary).
 * 
 * @param sessionId The session identifier.
 * @param updates Key-value updates to apply.
 */
export function updateSessionMetadata(sessionId: string, updates: Partial<SessionRecord>): void {
  console.info(`[SQL MEMORY] updateSessionMetadata called for session="${sessionId}" with fields:`, Object.keys(updates));
  const db = getSqlMemoryDb();
  const current = getSession(sessionId);
  if (!current) return;

  const now = new Date().toISOString();
  db.prepare(`
    UPDATE sessions
    SET 
      caller_language = COALESCE(?, caller_language),
      caller_language_code = COALESCE(?, caller_language_code),
      incident_type = COALESCE(?, incident_type),
      location = COALESCE(?, location),
      status = COALESCE(?, status),
      summary = COALESCE(?, summary),
      token_count = COALESCE(?, token_count),
      is_summarized = COALESCE(?, is_summarized),
      updated_at = ?
    WHERE session_id = ?
  `).run(
    updates.caller_language ?? null,
    updates.caller_language_code ?? null,
    updates.incident_type ?? null,
    updates.location ?? null,
    updates.status ?? null,
    updates.summary ?? null,
    updates.token_count ?? null,
    updates.is_summarized ?? null,
    now,
    sessionId
  );
}

/**
 * Records an executive summary generated by the Summarization Middleware in the SQL database.
 * 
 * @param sessionId The session identifier.
 * @param summaryText The synthesized summary text.
 * @param tokensSummarized Number of tokens summarized.
 * @param startTurn Starting turn index summarized.
 * @param endTurn Ending turn index summarized.
 */
export function recordSessionSummary(
  sessionId: string,
  summaryText: string,
  tokensSummarized: number,
  startTurn: number,
  endTurn: number
): void {
  console.info(`[SQL MEMORY] recordSessionSummary called for session="${sessionId}", tokensSummarized=${tokensSummarized}, turns ${startTurn}-${endTurn}`);
  const db = getSqlMemoryDb();
  const now = new Date().toISOString();

  // Insert into summaries audit log
  db.prepare(`
    INSERT INTO summaries (
      session_id, summary_text, tokens_summarized,
      range_start_turn, range_end_turn, created_at
    ) VALUES (?, ?, ?, ?, ?, ?)
  `).run(
    sessionId,
    summaryText,
    tokensSummarized,
    startTurn,
    endTurn,
    now
  );

  // Update session record
  db.prepare(`
    UPDATE sessions
    SET summary = ?, is_summarized = 1, updated_at = ?
    WHERE session_id = ?
  `).run(summaryText, now, sessionId);

  console.info(`[SQL MEMORY] Executive summary recorded for session "${sessionId}".`);
}

/**
 * Retrieves all executive summaries recorded for a given session.
 * 
 * @param sessionId The session identifier.
 * @returns Array of SummaryRecord.
 */
export function getSessionSummaries(sessionId: string): SummaryRecord[] {
  console.info(`[SQL MEMORY] getSessionSummaries called for session="${sessionId}"`);
  const db = getSqlMemoryDb();
  const rows = db.prepare("SELECT * FROM summaries WHERE session_id = ? ORDER BY id ASC").all(sessionId) as any[];
  return rows.map((r) => ({
    ...r,
    tokens_summarized: Number(r.tokens_summarized),
    range_start_turn: Number(r.range_start_turn),
    range_end_turn: Number(r.range_end_turn)
  }));
}
