"""
AURA (Autonomous Urgent Response Agent) - PostgreSQL Database & Native Pub/Sub
==============================================================================

This module implements native PostgreSQL publish/subscribe integration using asyncpg.
It connects to PostgreSQL, maintains a connection pool for transactional inserts,
and binds a dedicated async listener to the 'dispatch_events' channel.

Use Cases:
1. Pool management for inserting structured `DispatchReport` records produced by ADK tools.
2. Immediate capture of `pg_notify('dispatch_events', ...)` events triggered by the DB.
3. Sub-millisecond fan-out of new incidents to connected SSE dispatcher dashboards (zero Redis).
"""

import os
import asyncio
import json
import logging
from typing import Optional, AsyncGenerator, Callable, Set, List, Dict, Any
import asyncpg
from app.config import settings

logger = logging.getLogger("aura.database")

# Global asyncpg connection pool
_db_pool: Optional[asyncpg.Pool] = None

# Dedicated listener connection for LISTEN dispatch_events
_listener_conn: Optional[asyncpg.Connection] = None

# Set of active SSE queues subscribed to Postgres NOTIFY events
_sse_subscribers: Set[asyncio.Queue] = set()


async def init_db_pool() -> asyncpg.Pool:
    """
    Initializes the asyncpg connection pool using centralized configuration settings.

    Returns:
        asyncpg.Pool: The active connection pool.
    """
    global _db_pool
    if _db_pool is None:
        logger.info(
            f"init_db_pool: Initializing asyncpg connection pool (min={settings.database.pool_min_size}, "
            f"max={settings.database.pool_max_size})..."
        )
        _db_pool = await asyncpg.create_pool(
            dsn=settings.database.database_url,
            min_size=settings.database.pool_min_size,
            max_size=settings.database.pool_max_size,
            command_timeout=settings.database.command_timeout_sec
        )
        logger.info("init_db_pool: asyncpg connection pool established successfully.")
    return _db_pool


async def get_db_pool() -> asyncpg.Pool:
    """
    Returns or initializes the active asyncpg connection pool.

    Returns:
        asyncpg.Pool: Ready-to-use connection pool.
    """
    global _db_pool
    if _db_pool is None:
        await init_db_pool()
    return _db_pool


def _handle_postgres_notify(connection, pid: int, channel: str, payload: str):
    """
    Direct callback triggered by PostgreSQL whenever pg_notify('dispatch_events', ...) runs.
    Pushes the raw JSON event payload to all active SSE dispatcher queues with sub-millisecond latency.

    Args:
        connection: The asyncpg connection triggering the callback.
        pid: The backend server PID of the notifying PostgreSQL session.
        channel: The channel name (e.g. 'dispatch_events').
        payload: JSON-encoded string payload generated by `notify_dispatch_incident()`.
    """
    logger.info(f"[POSTGRES NOTIFY] Channel: {channel} (PID {pid}) -> Broadcast to {len(_sse_subscribers)} dispatcher clients")
    try:
        event_data = json.loads(payload)
    except Exception:
        event_data = {"event": "RAW_NOTIFY", "payload": payload}

    # Broadcast to all active SSE queues
    for queue in list(_sse_subscribers):
        try:
            queue.put_nowait(event_data)
        except asyncio.QueueFull:
            logger.warning("_handle_postgres_notify: Subscriber SSE queue full; skipping message.")


async def start_postgres_listener():
    """
    Maintains a dedicated PostgreSQL connection in LISTEN mode on the configured channel.
    """
    global _listener_conn
    logger.info(f"start_postgres_listener: Starting worker on channel '{settings.database.pubsub_channel}'...")
    try:
        _listener_conn = await asyncpg.connect(settings.database.database_url)
        await _listener_conn.add_listener(settings.database.pubsub_channel, _handle_postgres_notify)
        logger.info(f"[PUB/SUB ACTIVE] Listening natively to '{settings.database.pubsub_channel}' on PostgreSQL.")
    except Exception as e:
        logger.error(f"start_postgres_listener: Failed to bind PostgreSQL LISTEN worker: {e}", exc_info=True)


async def stop_postgres_listener():
    """
    Cleans up the listener connection and connection pool during application shutdown.
    """
    global _listener_conn, _db_pool
    logger.info("stop_postgres_listener: Releasing PostgreSQL resources...")
    if _listener_conn:
        try:
            await _listener_conn.remove_listener(settings.database.pubsub_channel, _handle_postgres_notify)
            await _listener_conn.close()
        except Exception:
            pass
        _listener_conn = None

    if _db_pool:
        await _db_pool.close()
        _db_pool = None
    logger.info("stop_postgres_listener: All connections and listeners successfully released.")


def register_sse_subscriber(queue: asyncio.Queue):
    """
    Registers an SSE client queue to receive Postgres notifications.

    Args:
        queue: The asyncio.Queue for the connected SSE response generator.
    """
    _sse_subscribers.add(queue)
    logger.info(f"register_sse_subscriber: Total active dispatcher subscribers = {len(_sse_subscribers)}")


def unregister_sse_subscriber(queue: asyncio.Queue):
    """
    Unregisters an SSE client queue upon browser disconnection.

    Args:
        queue: The asyncio.Queue to remove.
    """
    _sse_subscribers.discard(queue)
    logger.info(f"unregister_sse_subscriber: Remaining active subscribers = {len(_sse_subscribers)}")


async def fetch_recent_incidents(limit: int = 20) -> List[Dict[str, Any]]:
    """
    Retrieves recent emergency intake records for initial dashboard hydration.

    Args:
        limit: Maximum number of recent incident rows to fetch.

    Returns:
        List[Dict[str, Any]]: List of serialized incident dictionaries.
    """
    logger.info(f"fetch_recent_incidents: Querying top {limit} incidents...")
    pool = await get_db_pool()
    async with pool.acquire() as conn:
        records = await conn.fetch(
            """
            SELECT 
                id::text,
                call_id,
                incident_type,
                location,
                panic_index,
                casualties,
                status,
                caller_summary,
                tone_assessment,
                recommended_units,
                created_at
            FROM incidents
            ORDER BY created_at DESC
            LIMIT $1
            """,
            limit
        )
        logger.info(f"fetch_recent_incidents: Returned {len(records)} records.")
        return [dict(r) for r in records]
